const Discord = require ("discord.js"); // eslint-disable-line no-unused-vars
const Command = require("../base/Command.js");
const Settings = require("../models/settings.js");
const fs = require("fs");
const request = require("request");

class Send extends Command {
  constructor (client) {
    super(client, {
      name: "send",
      description: "Bulk sends webhooks of a specified type.",
      category: "Workers",
      usage: "<fnews, gnews, quest, votw> [content]",
      enabled: true,
      guildOnly: true,
      aliases: [],
      permLevel: "Worker",
      cooldown: 5,
      args: true
    });
  }

  async run (message, args, level, reply) { // eslint-disable-line no-unused-vars
    const option = args[0];

    if (option === "quest") {
      var dailyQuest = fs.readFileSync("dailyQuest.json", { encoding: "utf8" });
      dailyQuest = JSON.parse(dailyQuest);

      var totalCost = (parseInt(dailyQuest.item1.price) / parseInt(dailyQuest.item1.quantity) * parseInt(dailyQuest.item1.needed)) + (parseInt(dailyQuest.item2.price) / parseInt(dailyQuest.item2.quantity) * parseInt(dailyQuest.item2.needed));
      const embed = new Discord.MessageEmbed()
        .setAuthor("Today's Daily Quest", "https://cdn.discordapp.com/emojis/619959927120855060.png?v=1")

          .setFooter(message.author.tag, message.author.displayAvatarURL({dyanmic: true}))

          .addField("Daily Quests Items", `${dailyQuest.item1.needed} ${dailyQuest.item1.name} for ${dailyQuest.item1.price}<:wl:881764640751763517>
${dailyQuest.item2.needed} ${dailyQuest.item2.name} for ${dailyQuest.item2.price} <:wl:881764640751763517>`)

          .addField("Estimated Daily Quest Cost:", `<:wl:881764640751763517> ${`${totalCost.toFixed(2)}`.replace(".", ",").replace(",00", "")} World Locks`)

          .setTimestamp()

          .setColor("GREEN")
      .setFooter('Item price is subject to change based on demand | Generated by Myth#0001')
      

      const msg = await reply("<a:loadings:882121935755018260> Sending daily news are being sent, this may take a while...");
      await this.client.sendWebhook(embed, "dailyQuestChannel", "quest");
      msg.edit("<:greentick:912154637522583642> The daily news announcement has been sent.");
    } else if (option === "votw") {
      return reply("❓ At this point in time, VOTW webhook has been disabled until further notice.");
      // ! -- Here Goes Code for VOTW -- !
    } else if (option === "status") {
      return reply("❓ At this point in time, status webhook has been disabled until further notice.");
      // ! -- Here Goes Code for status -- !
    } else if (option === "fnews") {
      const description = args.splice(1).join(" ");
      if (!description) return reply("Missing contents.");

      const embed = new Discord.MessageEmbed()
        .setTitle("Forum Newsletter")
        .setDescription(description)
        .setColor("GREEN")
        .setTimestamp();

      const msg = await reply("<a:loadings:882121935755018260> Sending daily news are being sent, this may take a while...");
      await this.client.sendWebhook(embed, "forumNewsChannel", "forum-news");
      msg.edit("<:greentick:912154637522583642> The forum news announcement has been sent.");
    } else if (option === "update") {
      if (!args[1]) return reply("Missing contents.");

      var [content, url] = args.slice(1).join(" ").split("|");
      if (!url && message.attachments.first()) url = message.attachments.first().proxyURL; 
      if (!content || !url) return reply("Bad format.");

      const embed = new Discord.MessageEmbed()
        .setTitle("Growtopia Newsletter")
        .setDescription(content)
        .setImage(url)
        .setColor("GREEN")
        .setTimestamp();

      const msg = await reply("<a:loadings:882121935755018260> Sending daily news are being sent, this may take a while...");
      await this.client.sendWebhook(embed, "gameNewsChannel", "game-news");
      msg.edit("<:greentick:912154637522583642> The update notification has been sent.");
    }
  }
}

module.exports = Send;

function isFloat(n){
  return Number(n) === n && n % 1 !== 0;
}